export { default as Home } from './Home'
export { default as Services1 } from './services/Services1'
export { default as Services2 } from './services/Services2'
export { default as Services3 } from './services/Services3'
export { default as About } from './about/About'